version: "3.8"

services:
  db:
    image: postgres:16
    restart: unless-stopped
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      URL_DATABASE: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db

  web:
    build: ./web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - FASTAPI_URI=${FASTAPI_URI:-"http://localhost:5000"}
    depends_on:
      - api

volumes:
  postgres_data:
